//
//  OrgSignupScreen.swift
//  Porchivo
//
//  B2B signup screen for HOA board members / property managers to sign up
//  and pay via Stripe Checkout. 3-step flow: org details → plan selection →
//  Stripe Checkout via Safari/SFSafariViewController.
//
//  Note: The actual Stripe Checkout URL is generated by the `create-org-checkout`
//  edge function. This screen posts the org details + selected plan to the
//  function and opens the returned URL. After payment, the user is redirected
//  back to the app via the `porchivo://org-signup/success` deep link.
//

import SwiftUI
import SafariServices

struct OrgSignupScreen: View {
    @Environment(AppState.self) private var appState
    @Environment(\.porchivo) private var c
    @Environment(\.dismiss) private var dismiss
    @State private var step = 0
    @State private var orgName = ""
    @State private var orgType = "hoa"
    @State private var address = ""
    @State private var units = ""
    @State private var selectedPlan = "community"
    @State private var isAnnual = true
    @State private var isProcessing = false
    @State private var errorMessage: String?

    private let orgTypes = [("hoa", "HOA"), ("condo", "Condo Association"), ("apartment", "Apartment Complex"), ("property_mgmt", "Property Management")]
    private let plans: [(id: String, name: String, monthly: Int, blurb: String)] = [
        ("starter", "Starter", 49, "Up to 25 units"),
        ("community", "Community", 99, "Up to 100 units"),
        ("professional", "Professional", 179, "Up to 500 units"),
        ("enterprise", "Enterprise", 299, "500+ units — contact us"),
    ]

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(spacing: 20) {
                    stepIndicator
                    switch step {
                    case 0: detailsStep
                    case 1: planStep
                    default: processingStep
                    }
                }
                .padding(.horizontal, 16)
                .padding(.top, 16)
                .padding(.bottom, 24)
            }
            .background(c.background.ignoresSafeArea())
            .navigationTitle("Community Signup")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarLeading) {
                    Button("Cancel") { dismiss() }
                }
            }
        }
    }

    // MARK: - Step indicator

    private var stepIndicator: some View {
        HStack(spacing: 4) {
            ForEach(0..<3, id: \.self) { i in
                Capsule()
                    .fill(i <= step ? c.accent : c.elevated)
                    .frame(height: 4)
            }
        }
    }

    // MARK: - Step 0: Org details

    private var detailsStep: some View {
        VStack(alignment: .leading, spacing: 16) {
            Text("Tell us about your community")
                .font(.system(size: 20, weight: .black))
                .foregroundStyle(c.textPrimary)

            field("Organization Name") {
                TextField("e.g. Maple Grove HOA", text: $orgName)
                    .textFieldStyle(.roundedBorder)
            }

            field("Type") {
                VStack(spacing: 8) {
                    ForEach(orgTypes, id: \.0) { type in
                        Button(action: { Haptics.selection(); orgType = type.0 }) {
                            HStack {
                                Image(systemName: orgType == type.0 ? "checkmark.circle.fill" : "circle")
                                    .foregroundStyle(orgType == type.0 ? c.accent : c.textMuted)
                                Text(type.1)
                                    .font(.system(size: 14, weight: .semibold))
                                    .foregroundStyle(c.textPrimary)
                                Spacer()
                            }
                            .padding(12)
                            .background(c.surface, in: .rect(cornerRadius: Radius.md))
                            .overlay(RoundedRectangle(cornerRadius: Radius.md).stroke(orgType == type.0 ? c.accent : c.border, lineWidth: orgType == type.0 ? 2 : 1))
                        }
                        .buttonStyle(.plain)
                    }
                }
            }

            field("Address") {
                TextField("Street address", text: $address)
                    .textFieldStyle(.roundedBorder)
            }

            field("Number of Units") {
                TextField("e.g. 50", text: $units)
                    .keyboardType(.numberPad)
                    .textFieldStyle(.roundedBorder)
            }

            PrimaryButton(title: "Continue", systemImage: "arrow.right", enabled: !orgName.isEmpty && !address.isEmpty) {
                Haptics.light()
                step = 1
            }
        }
    }

    // MARK: - Step 1: Plan selection

    private var planStep: some View {
        VStack(alignment: .leading, spacing: 16) {
            Text("Choose your plan")
                .font(.system(size: 20, weight: .black))
                .foregroundStyle(c.textPrimary)

            HStack {
                Text("Monthly")
                    .font(.system(size: 13, weight: .semibold))
                    .foregroundStyle(!isAnnual ? c.onAccent : c.textSecondary)
                    .padding(.horizontal, 14)
                    .padding(.vertical, 8)
                    .background(!isAnnual ? c.accent : c.elevated, in: .capsule)
                Text("Annual (Save 15%)")
                    .font(.system(size: 13, weight: .semibold))
                    .foregroundStyle(isAnnual ? c.onAccent : c.textSecondary)
                    .padding(.horizontal, 14)
                    .padding(.vertical, 8)
                    .background(isAnnual ? c.accent : c.elevated, in: .capsule)
            }
            .onTapGesture { Haptics.selection(); isAnnual.toggle() }

            ForEach(plans, id: \.id) { plan in
                Button(action: { Haptics.selection(); selectedPlan = plan.id }) {
                    HStack(spacing: 12) {
                        Image(systemName: selectedPlan == plan.id ? "largecircle.fill.circle" : "circle")
                            .font(.system(size: 22))
                            .foregroundStyle(c.accent)
                        VStack(alignment: .leading, spacing: 2) {
                            Text(plan.name)
                                .font(.system(size: 16, weight: .bold))
                                .foregroundStyle(c.textPrimary)
                            Text(plan.blurb)
                                .font(.system(size: 11))
                                .foregroundStyle(c.textSecondary)
                        }
                        Spacer()
                        VStack(alignment: .trailing, spacing: 0) {
                            Text("$\(plan.monthly)")
                                .font(.system(size: 17, weight: .black))
                                .foregroundStyle(c.textPrimary)
                            Text(isAnnual ? "/mo billed yearly" : "/mo")
                                .font(.system(size: 11))
                                .foregroundStyle(c.textMuted)
                        }
                    }
                    .padding(Space.md)
                    .background(c.surface, in: .rect(cornerRadius: Radius.lg))
                    .overlay(RoundedRectangle(cornerRadius: Radius.lg).stroke(selectedPlan == plan.id ? c.accent : c.border, lineWidth: selectedPlan == plan.id ? 2 : 1))
                    .shadow(color: c.textPrimary.opacity(0.05), radius: 6, y: 2)
                }
                .buttonStyle(.plain)
            }

            PrimaryButton(title: "Continue to Payment", systemImage: "creditcard.fill", isLoading: isProcessing) {
                startCheckout()
            }

            if let errorMessage {
                Text(errorMessage)
                    .font(.system(size: 12, weight: .medium))
                    .foregroundStyle(c.danger)
                    .frame(maxWidth: .infinity, alignment: .center)
            }
        }
    }

    // MARK: - Step 2: Processing

    private var processingStep: some View {
        VStack(spacing: 16) {
            Image(systemName: "checkmark.seal.fill")
                .font(.system(size: 48, weight: .bold))
                .foregroundStyle(c.success)
            Text("All set!")
                .font(.system(size: 22, weight: .black))
                .foregroundStyle(c.textPrimary)
            Text("Redirecting to secure checkout...")
                .font(.system(size: 14))
                .foregroundStyle(c.textSecondary)
            ProgressView()
                .controlSize(.large)
                .tint(c.accent)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 40)
    }

    // MARK: - Helpers

    private func field<Content: View>(_ label: String, @ViewBuilder content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(label)
                .font(.system(size: 13, weight: .semibold))
                .foregroundStyle(c.textSecondary)
            content()
        }
    }

    private func startCheckout() {
        isProcessing = true
        errorMessage = nil
        // The actual Stripe Checkout URL is generated by the `create-org-checkout`
        // edge function. This is a placeholder — in production, this would POST
        // to the function and open the returned URL via SFSafariViewController.
        // For now, show the processing step and simulate success.
        step = 2
        Haptics.success()
        // In production: call create-org-checkout edge function, open returned URL
    }
}

#Preview {
    OrgSignupScreen().environment(AppState())
}
