//
//  OrgSignupScreen.swift
//  Porchivo
//
//  B2B signup screen for HOA board members / property managers to sign up
//  and pay via Stripe Checkout. 3-step flow: org details → plan selection →
//  Stripe Checkout via ASWebAuthenticationSession → success/cancelled.
//
//  The actual Stripe Checkout URL is generated by the `create-org-checkout`
//  edge function. This screen posts org details + selected plan to the
//  function, opens the returned URL via ASWebAuthenticationSession, then
//  calls `confirm-org-signup` to verify payment and activate the org.
//

import SwiftUI
import AuthenticationServices

struct OrgSignupScreen: View {
    @Environment(AppState.self) private var appState
    @Environment(\.porchivo) private var c
    @Environment(\.dismiss) private var dismiss
    @State private var step: SignupStep = .details
    @State private var orgName = ""
    @State private var orgType = "hoa"
    @State private var address = ""
    @State private var city = ""
    @State private var stateField = ""
    @State private var zip = ""
    @State private var totalUnits = ""
    @State private var selectedPlan = "community"
    @State private var isAnnual = true
    @State private var isProcessing = false
    @State private var errorMessage: String?
    @State private var checkoutSessionId: String?
    @State private var checkoutOrgId: String?
    @State private var inviteCode: String?
    @State private var createdOrgName = ""

    private let orgTypes: [(id: String, label: String)] = [
        ("hoa", "HOA"),
        ("condo", "Condo Association"),
        ("multifamily", "Multifamily"),
        ("property_management", "Property Management"),
    ]
    private let plans: [(id: String, name: String, monthly: Int, blurb: String)] = [
        ("starter", "Starter", 79, "Up to 50 units"),
        ("community", "Community", 199, "Up to 200 units"),
        ("professional", "Professional", 399, "Up to 500 units"),
        ("enterprise", "Enterprise", 599, "Up to 2,000 units"),
    ]

    private let successRedirect = "porchivo://org-signup/success"
    private let cancelRedirect = "porchivo://org-signup/cancelled"

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(spacing: 20) {
                    stepIndicator
                    switch step {
                    case .details:
                        detailsStep
                    case .plan:
                        planStep
                    case .launching:
                        launchingStep
                    case .confirming:
                        confirmingStep
                    case .success:
                        successStep
                    case .cancelled:
                        cancelledStep
                    }
                }
                .padding(.horizontal, 16)
                .padding(.top, 16)
                .padding(.bottom, 24)
            }
            .background(c.background.ignoresSafeArea())
            .navigationTitle("Create Community")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarLeading) {
                    Button("Cancel") { dismiss() }
                }
            }
        }
    }

    // MARK: - Step indicator

    private var stepIndicator: some View {
        HStack(spacing: 4) {
            ForEach(0..<3, id: \.self) { i in
                Capsule()
                    .fill(i <= stepIndex ? c.accent : c.elevated)
                    .frame(height: 4)
            }
        }
    }

    private var stepIndex: Int {
        switch step {
        case .details: return 0
        case .plan: return 1
        default: return 2
        }
    }

    // MARK: - Step: Details

    private var detailsStep: some View {
        VStack(alignment: .leading, spacing: 16) {
            Text("Tell us about your community")
                .font(.system(size: 20, weight: .black))
                .foregroundStyle(c.textPrimary)

            field("Organization Name") {
                TextField("e.g. Maple Grove HOA", text: $orgName)
                    .textFieldStyle(.roundedBorder)
            }

            field("Type") {
                VStack(spacing: 8) {
                    ForEach(orgTypes, id: \.id) { type in
                        Button(action: { Haptics.selection(); orgType = type.id }) {
                            HStack {
                                Image(systemName: orgType == type.id ? "checkmark.circle.fill" : "circle")
                                    .foregroundStyle(orgType == type.id ? c.accent : c.textMuted)
                                Text(type.label)
                                    .font(.system(size: 14, weight: .semibold))
                                    .foregroundStyle(c.textPrimary)
                                Spacer()
                            }
                            .padding(12)
                            .background(c.surface, in: .rect(cornerRadius: Radius.md))
                            .overlay(RoundedRectangle(cornerRadius: Radius.md).stroke(orgType == type.id ? c.accent : c.border, lineWidth: orgType == type.id ? 2 : 1))
                        }
                        .buttonStyle(.plain)
                    }
                }
            }

            field("Street Address") {
                TextField("123 Main St", text: $address)
                    .textFieldStyle(.roundedBorder)
            }

            HStack(spacing: 8) {
                field("City") {
                    TextField("Austin", text: $city)
                        .textFieldStyle(.roundedBorder)
                }
                field("State") {
                    TextField("TX", text: $stateField)
                        .textInputAutocapitalization(.characters)
                        .textFieldStyle(.roundedBorder)
                }
                field("ZIP") {
                    TextField("78701", text: $zip)
                        .keyboardType(.numberPad)
                        .textFieldStyle(.roundedBorder)
                }
            }

            field("Total Units (optional)") {
                TextField("e.g. 50", text: $totalUnits)
                    .keyboardType(.numberPad)
                    .textFieldStyle(.roundedBorder)
            }

            PrimaryButton(title: "Continue to Plan Selection", systemImage: "arrow.right",
                          enabled: !orgName.isEmpty && !address.isEmpty && !city.isEmpty && !stateField.isEmpty && !zip.isEmpty) {
                Haptics.light()
                step = .plan
            }
        }
    }

    // MARK: - Step: Plan

    private var planStep: some View {
        VStack(alignment: .leading, spacing: 16) {
            Text("Choose your plan")
                .font(.system(size: 20, weight: .black))
                .foregroundStyle(c.textPrimary)

            // B2B disclaimer — clarifies this is an organization-level service,
            // not a consumer in-app subscription (Apple Guideline 3.1.3(e)).
            HStack(spacing: 10) {
                Image(systemName: "building.2.fill")
                    .font(.system(size: 14, weight: .bold))
                    .foregroundStyle(c.accent)
                Text("Plans are billed to your organization for community-wide access. Residents always use Porchivo free.")
                    .font(.system(size: 11, weight: .medium))
                    .foregroundStyle(c.textSecondary)
                    .fixedSize(horizontal: false, vertical: true)
            }
            .padding(12)
            .background(c.elevated, in: .rect(cornerRadius: Radius.md))

            HStack {
                Button(action: { Haptics.selection(); isAnnual = false }) {
                    Text("Monthly")
                        .font(.system(size: 13, weight: .semibold))
                        .foregroundStyle(!isAnnual ? c.onAccent : c.textSecondary)
                        .padding(.horizontal, 14)
                        .padding(.vertical, 8)
                        .background(!isAnnual ? c.accent : c.elevated, in: .capsule)
                }
                .buttonStyle(.plain)
                Button(action: { Haptics.selection(); isAnnual = true }) {
                    HStack(spacing: 4) {
                        Text("Annual")
                            .font(.system(size: 13, weight: .semibold))
                            .foregroundStyle(isAnnual ? c.onAccent : c.textSecondary)
                        Text("Save 20%")
                            .font(.system(size: 10, weight: .bold))
                            .foregroundStyle(isAnnual ? c.onAccent : c.success)
                            .padding(.horizontal, 6)
                            .padding(.vertical, 2)
                            .background(isAnnual ? Color.white.opacity(0.2) : c.successSoft, in: .capsule)
                    }
                    .padding(.horizontal, 14)
                    .padding(.vertical, 8)
                    .background(isAnnual ? c.accent : c.elevated, in: .capsule)
                }
                .buttonStyle(.plain)
            }

            ForEach(plans, id: \.id) { plan in
                Button(action: { Haptics.selection(); selectedPlan = plan.id }) {
                    HStack(spacing: 12) {
                        Image(systemName: selectedPlan == plan.id ? "largecircle.fill.circle" : "circle")
                            .font(.system(size: 22))
                            .foregroundStyle(c.accent)
                        VStack(alignment: .leading, spacing: 2) {
                            Text(plan.name)
                                .font(.system(size: 16, weight: .bold))
                                .foregroundStyle(c.textPrimary)
                            Text(plan.blurb)
                                .font(.system(size: 11))
                                .foregroundStyle(c.textSecondary)
                        }
                        Spacer()
                        VStack(alignment: .trailing, spacing: 0) {
                            Text("$\(plan.monthly)")
                                .font(.system(size: 17, weight: .black))
                                .foregroundStyle(c.textPrimary)
                            Text(isAnnual ? "/mo billed yearly" : "/mo")
                                .font(.system(size: 11))
                                .foregroundStyle(c.textMuted)
                        }
                    }
                    .padding(Space.md)
                    .background(c.surface, in: .rect(cornerRadius: Radius.lg))
                    .overlay(RoundedRectangle(cornerRadius: Radius.lg).stroke(selectedPlan == plan.id ? c.accent : c.border, lineWidth: selectedPlan == plan.id ? 2 : 1))
                    .shadow(color: c.textPrimary.opacity(0.05), radius: 6, y: 2)
                }
                .buttonStyle(.plain)
            }

            PrimaryButton(title: "Continue to Payment", systemImage: "creditcard.fill", isLoading: isProcessing) {
                startCheckout()
            }

            if let errorMessage {
                Text(errorMessage)
                    .font(.system(size: 12, weight: .medium))
                    .foregroundStyle(c.danger)
                    .frame(maxWidth: .infinity, alignment: .center)
            }
        }
    }

    // MARK: - Step: Launching

    private var launchingStep: some View {
        VStack(spacing: 16) {
            ProgressView()
                .controlSize(.large)
                .tint(c.accent)
            Text("Preparing checkout…")
                .font(.system(size: 18, weight: .bold))
                .foregroundStyle(c.textPrimary)
            Text("Setting up your community and Stripe payment session.")
                .font(.system(size: 14))
                .foregroundStyle(c.textSecondary)
                .multilineTextAlignment(.center)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 40)
    }

    // MARK: - Step: Confirming

    private var confirmingStep: some View {
        VStack(spacing: 16) {
            ProgressView()
                .controlSize(.large)
                .tint(c.accent)
            Text("Verifying payment…")
                .font(.system(size: 18, weight: .bold))
                .foregroundStyle(c.textPrimary)
            Text("Confirming your subscription with Stripe. This usually takes a few seconds.")
                .font(.system(size: 14))
                .foregroundStyle(c.textSecondary)
                .multilineTextAlignment(.center)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 40)
    }

    // MARK: - Step: Success

    private var successStep: some View {
        VStack(spacing: 16) {
            Image(systemName: "checkmark.seal.fill")
                .font(.system(size: 48, weight: .bold))
                .foregroundStyle(c.success)
            Text("Community is live!")
                .font(.system(size: 22, weight: .black))
                .foregroundStyle(c.textPrimary)
            Text("\(createdOrgName) is now on Porchivo. Your subscription is active and community features are unlocked.")
                .font(.system(size: 14))
                .foregroundStyle(c.textSecondary)
                .multilineTextAlignment(.center)

            if let inviteCode {
                VStack(spacing: 8) {
                    Text("YOUR INVITE CODE")
                        .font(.system(size: 11, weight: .bold))
                        .foregroundStyle(c.textMuted)
                    Text(inviteCode)
                        .font(.system(size: 32, weight: .heavy))
                        .foregroundStyle(c.accent)
                        .tracking(4)
                    Text("Share this code with residents so they can join your community in the app.")
                        .font(.system(size: 12))
                        .foregroundStyle(c.textMuted)
                        .multilineTextAlignment(.center)
                }
                .padding(20)
                .background(c.surface, in: .rect(cornerRadius: Radius.lg))
                .overlay(RoundedRectangle(cornerRadius: Radius.lg).stroke(c.border, lineWidth: 1))
            }

            PrimaryButton(title: "Go to Dashboard", systemImage: "arrow.right", enabled: true) {
                Haptics.light()
                dismiss()
            }
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 20)
    }

    // MARK: - Step: Cancelled

    private var cancelledStep: some View {
        VStack(spacing: 16) {
            Image(systemName: "creditcard")
                .font(.system(size: 36, weight: .bold))
                .foregroundStyle(c.textMuted)
            Text("Payment not completed")
                .font(.system(size: 20, weight: .bold))
                .foregroundStyle(c.textPrimary)
            Text("You closed the checkout before finishing. Your community has been saved but isn't active yet.")
                .font(.system(size: 14))
                .foregroundStyle(c.textSecondary)
                .multilineTextAlignment(.center)

            if let errorMessage {
                Text(errorMessage)
                    .font(.system(size: 12, weight: .medium))
                    .foregroundStyle(c.danger)
                    .frame(maxWidth: .infinity, alignment: .center)
            }

            PrimaryButton(title: "I Already Paid — Verify", systemImage: "checkmark.shield.fill", enabled: true) {
                guard let sid = checkoutSessionId, let oid = checkoutOrgId else { return }
                Haptics.light()
                step = .confirming
                Task { await confirmSignup(sessionId: sid, orgId: oid) }
            }

            Button(action: { Haptics.selection(); step = .plan; errorMessage = nil }) {
                Text("Back to plan selection")
                    .font(.system(size: 14, weight: .medium))
                    .foregroundStyle(c.textSecondary)
            }
            .buttonStyle(.plain)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 20)
    }

    // MARK: - Helpers

    private func field<Content: View>(_ label: String, @ViewBuilder content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(label)
                .font(.system(size: 13, weight: .semibold))
                .foregroundStyle(c.textSecondary)
            content()
        }
    }

    // MARK: - Checkout flow

    private func startCheckout() {
        isProcessing = true
        errorMessage = nil
        step = .launching

        Task { await launchCheckout() }
    }

    private func launchCheckout() async {
        let units = Int(totalUnits)
        let result = await appState.createOrgCheckout(
            name: orgName.trimmingCharacters(in: .whitespaces),
            type: orgType,
            address: address.trimmingCharacters(in: .whitespaces),
            city: city.trimmingCharacters(in: .whitespaces),
            state: stateField.uppercased(),
            zip: zip.trimmingCharacters(in: .whitespaces),
            totalUnits: units,
            planTier: selectedPlan,
            billingCycle: isAnnual ? "annual" : "monthly",
            returnUrl: successRedirect
        )

        await MainActor.run {
            isProcessing = false
        }

        switch result {
        case .success(let response):
            checkoutSessionId = response.sessionId
            checkoutOrgId = response.orgId

            // Open Stripe Checkout via ASWebAuthenticationSession
            let session = ASWebAuthSessionWrapper(
                url: URL(string: response.checkoutUrl)!,
                callbackScheme: "porchivo"
            ) { callbackURL, error in
                Task { @MainActor in
                    if let error {
                        errorMessage = error.localizedDescription
                        step = .cancelled
                        return
                    }
                    guard let callbackURL else {
                        step = .cancelled
                        return
                    }
                    let urlString = callbackURL.absoluteString
                    if urlString.hasPrefix(successRedirect) {
                        step = .confirming
                        // Extract session_id and org_id from the redirect URL
                        let comps = URLComponents(url: callbackURL, resolvingAgainstBaseURL: false)
                        let sid = comps?.queryItems?.first(where: { $0.name == "session_id" })?.value ?? response.sessionId
                        let oid = comps?.queryItems?.first(where: { $0.name == "org_id" })?.value ?? response.orgId
                        await confirmSignup(sessionId: sid, orgId: oid)
                    } else if urlString.hasPrefix(cancelRedirect) {
                        step = .cancelled
                    } else {
                        step = .cancelled
                    }
                }
            }
            session.start()

        case .failure(let error):
            await MainActor.run {
                errorMessage = error.localizedDescription
                step = .cancelled
            }
        }
    }

    private func confirmSignup(sessionId: String, orgId: String) async {
        let result = await appState.confirmOrgSignup(
            sessionId: sessionId,
            orgId: orgId
        )

        await MainActor.run {
            switch result {
            case .success(let response):
                if response.success == true {
                    inviteCode = response.org?.inviteCode
                    createdOrgName = response.org?.name ?? orgName
                    Haptics.success()
                    step = .success
                    // Refresh org context so the tab layout switches to community tier
                    Task { @MainActor in
                        await appState.refreshOrgContext()
                    }
                } else {
                    errorMessage = response.error ?? "Payment verification failed"
                    step = .cancelled
                }
            case .failure(let error):
                errorMessage = error.localizedDescription
                step = .cancelled
            }
        }
    }
}

// MARK: - Step enum

private enum SignupStep: Equatable {
    case details
    case plan
    case launching
    case confirming
    case success
    case cancelled
}

// MARK: - ASWebAuthenticationSession wrapper

/// Wraps ASWebAuthenticationSession with a coordinator so it can present
/// the Safari-based authentication sheet and capture the callback redirect.
@MainActor
final class ASWebAuthSessionWrapper: NSObject, ASWebAuthenticationPresentationContextProviding {
    private let session: ASWebAuthenticationSession
    private let callback: (URL?, Error?) -> Void

    init(url: URL, callbackScheme: String, callback: @escaping (URL?, Error?) -> Void) {
        self.callback = callback
        self.session = ASWebAuthenticationSession(url: url, callbackURLScheme: callbackScheme) { url, error in
            Task { @MainActor in
                callback(url, error)
            }
        }
        super.init()
        session.presentationContextProvider = self
        session.prefersEphemeralWebBrowserSession = false
    }

    func start() {
        _ = session.start()
    }

    nonisolated func presentationAnchor(for session: ASWebAuthenticationSession) -> ASPresentationAnchor {
        // Return the key window of the current scene
        MainActor.assumeIsolated {
            UIApplication.shared.connectedScenes
                .compactMap { $0 as? UIWindowScene }
                .first { $0.activationState == .foregroundActive }?
                .windows.first ?? ASPresentationAnchor()
        }
    }
}

#Preview {
    OrgSignupScreen().environment(AppState())
}
