#!/usr/bin/env node
/**
 * Auto-refresh generated blocks across the project's docs from the live codebase.
 *
 * This is a generic engine: each entry in TARGETS points at a markdown file and a
 * marker id, plus a function that produces the block body from a freshly scanned
 * view of the repo. Any doc can opt in just by embedding a marker pair:
 *
 *   <!-- AUTO-GENERATED:<ID>:START -->
 *   ...anything here is overwritten on refresh...
 *   <!-- AUTO-GENERATED:<ID>:END -->
 *
 * Currently refreshed:
 *   - README.md         (SNAPSHOT)     — at-a-glance counts + screen list
 *   - MAINTENANCE.md     (SCREEN-INDEX) — full current screen index for the founder guide
 *
 * Deliberately NOT auto-refreshed: SECURITY.md and STRIPE_SETUP.md are point-in-time
 * records (a dated audit and a manual setup runbook) — rewriting them automatically
 * would destroy their intent, so they stay hand-maintained.
 *
 * Run manually with `node scripts/refresh-docs.mjs` or on a schedule via
 * .github/workflows/refresh-readme.yml. Zero dependencies — Node built-ins only.
 */
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, dirname, extname, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SCRIPT_REF = "scripts/refresh-docs.mjs";

const IGNORE_DIRS = new Set([
  "node_modules",
  ".git",
  ".rork",
  "dist",
  "build",
  ".expo",
  "ios",
  "android",
  "coverage",
]);

/** Recursively walk a directory, returning file paths that match an extension set. */
function walk(dir, exts, acc = []) {
  if (!existsSync(dir)) return acc;
  for (const entry of readdirSync(dir)) {
    if (entry.startsWith(".") && entry !== ".github") continue;
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      if (IGNORE_DIRS.has(entry)) continue;
      walk(full, exts, acc);
    } else if (exts.has(extname(entry))) {
      acc.push(full);
    }
  }
  return acc;
}

/** Count files inside a directory matching an extension set. */
function countFiles(dir, exts, recursive = true) {
  if (!existsSync(dir)) return 0;
  if (recursive) return walk(dir, exts).length;
  return readdirSync(dir).filter(
    (f) => exts.has(extname(f)) && statSync(join(dir, f)).isFile()
  ).length;
}

const tsx = new Set([".ts", ".tsx"]);

/** Top-level Expo Router screen names (route files directly under app/). */
function listTopLevelScreens() {
  const appDir = join(ROOT, "expo", "app");
  if (!existsSync(appDir)) return [];
  return readdirSync(appDir)
    .filter((f) => f.endsWith(".tsx") && !f.startsWith("_") && !f.startsWith("+"))
    .map((f) => f.replace(/\.tsx$/, ""))
    .sort();
}

/** Every Expo Router route file (including nested groups), as app-relative paths. */
function listAllRoutes() {
  const appDir = join(ROOT, "expo", "app");
  if (!existsSync(appDir)) return [];
  return walk(appDir, new Set([".tsx"]))
    .map((f) => relative(appDir, f).split(/[\\/]/).join("/"))
    .filter((p) => {
      const base = p.split("/").pop() ?? "";
      return !base.startsWith("_") && !base.startsWith("+");
    })
    .sort();
}

/** Count backend migration SQL files. */
function backendMigrations() {
  const dir = join(ROOT, "supabase");
  if (!existsSync(dir)) return 0;
  return readdirSync(dir).filter((f) => f.endsWith(".sql")).length;
}

/** Read dependency count from a package.json. */
function depCount(pkgPath) {
  if (!existsSync(pkgPath)) return 0;
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
    return Object.keys(pkg.dependencies ?? {}).length;
  } catch {
    return 0;
  }
}

function stamp() {
  const now = new Date();
  return `${now.toISOString().slice(0, 10)} ${now.toISOString().slice(11, 16)} UTC`;
}

/** README "at a glance" snapshot. */
function buildSnapshot() {
  const screens = listTopLevelScreens();
  const screensLine =
    screens.length > 0 ? screens.map((s) => `\`${s}\``).join(", ") : "_none detected_";
  return `_Last refreshed: **${stamp()}** — generated by \`${SCRIPT_REF}\`._

**At a glance**

| Area | Count |
|------|------:|
| Mobile screens (\`expo/app/\`) | ${screens.length} |
| Mobile components (\`expo/components/\`) | ${countFiles(join(ROOT, "expo", "components"), tsx)} |
| Shared libs (\`expo/lib/\`) | ${countFiles(join(ROOT, "expo", "lib"), tsx, false)} |
| State stores/providers (\`expo/store/\`) | ${countFiles(join(ROOT, "expo", "store"), tsx, false)} |
| Marketing site pages (\`web-porchivo-web/\`) | ${countFiles(join(ROOT, "web-porchivo-web", "src", "pages"), tsx, false)} |
| Backend migrations (\`supabase/\`) | ${backendMigrations()} |
| Mobile dependencies | ${depCount(join(ROOT, "expo", "package.json"))} |
| Web dependencies | ${depCount(join(ROOT, "web-porchivo-web", "package.json"))} |

**Current screens:** ${screensLine}`;
}

/** MAINTENANCE.md full screen index (auto-kept current as routes are added/removed). */
function buildScreenIndex() {
  const routes = listAllRoutes();
  const lines = routes.map((r) => `| \`${r}\` | \`app/${r}\` |`).join("\n");
  return `> _Auto-generated from \`expo/app/\` on **${stamp()}** by \`${SCRIPT_REF}\`. The
> curated table above stays hand-written; this list is the complete, always-current
> set of route files so nothing silently goes missing as the app grows._

**${routes.length} route screens detected:**

| Route | File |
|-------|------|
${lines}`;
}

const TARGETS = [
  { file: "README.md", id: "SNAPSHOT", build: buildSnapshot },
  { file: "MAINTENANCE.md", id: "SCREEN-INDEX", build: buildScreenIndex },
];

let changed = 0;
let missing = 0;

for (const target of TARGETS) {
  const path = join(ROOT, target.file);
  if (!existsSync(path)) {
    console.warn(`Skip ${target.file} — file not found.`);
    continue;
  }
  const START = `<!-- AUTO-GENERATED:${target.id}:START -->`;
  const END = `<!-- AUTO-GENERATED:${target.id}:END -->`;
  const text = readFileSync(path, "utf8");
  const s = text.indexOf(START);
  const e = text.indexOf(END);
  if (s === -1 || e === -1) {
    console.warn(`Skip ${target.file} — markers ${target.id} not found.`);
    missing += 1;
    continue;
  }
  const block = `${START}\n${target.build()}\n${END}`;
  const next = text.slice(0, s) + block + text.slice(e + END.length);
  if (next === text) {
    console.log(`${target.file} (${target.id}) already up to date.`);
    continue;
  }
  writeFileSync(path, next);
  console.log(`${target.file} (${target.id}) refreshed at ${stamp()}.`);
  changed += 1;
}

if (missing > 0 && changed === 0) {
  // Surface a non-zero exit only when nothing could be refreshed at all,
  // so CI fails loudly if every marker pair was removed by mistake.
  process.exit(1);
}
